// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
